//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por TiendaCPP.rc
//
#define IDC_MYICON                      2
#define IDD_TIENDACPP_DIALOG            102
#define IDD_ABOUTBOX_NEW                102
#define IDD_HISTORYBOX                  102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX_DEFAULT            103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDD_COTIZACIONBOX               106
#define IDI_TIENDACPP                   107
#define IDD_ABOUTBOX_NEW2               107
#define IDD_SETTINGSBOX                 107
#define IDI_SMALL                       108
#define IDD_ADMIN_BOOKS                 108
#define IDC_TIENDACPP                   109
#define IDD_ADMIN_EXEMPLARIES           109
#define IDD_ADMIN_PARTNERS              110
#define IDR_MAINFRAME                   128
#define IDD_ABOUTBOX_SLABEL1            128
#define IDD_ABOUTBOX_SLABEL2            129
#define IDC_RADIO1                      1004
#define RBTN3_MANGA_CORTA               1004
#define RBTN_PARTNERTYPE_COMMON         1004
#define RBTN3_MANGA_LARGA               1005
#define IDC_RADIO3                      1005
#define RBTN_PARTNERTYPE_VIP            1005
#define RBTN4_CUELLO_COMUN              1006
#define RBTN4_CUELLO_MAO                1007
#define IDC_RADIO2                      1008
#define IDC_RADIO                       1008
#define RBTN4_PANTALON_COMUN            1008
#define RBTN4_COMUN                     1008
#define RBTN5_COMUN                     1008
#define RBTN4_CHUPIN                    1009
#define RBTN5_CHUPIN                    1009
#define RBTN2_SHIRT                     1010
#define RBTN2_PANT                      1011
#define CHK_MANGA                       1012
#define CHK_CUELLO                      1013
#define CHK_CHUPIN                      1014
#define RBTN_STANDAR                    1015
#define RBTN_PREMIUM                    1016
#define GBC_CLOTH                       1017
#define LBL_STOCK                       1018
#define GBC_QUALITY                     1019
#define GBC_PRICE                       1020
#define LBL_MONTO                       1022
#define INPF_PRICE                      1023
#define LBL_QUANTITY                    1024
#define INPF_QUANTITY                   1025
#define IDC_BUTTON1                     1026
#define LBL_QUANTITY2                   1026
#define BTN_ADD_BOOK                    1026
#define BTN_ADDBOOK_ADDBTN              1026
#define IDC_EDIT1                       1027
#define INPF_BOOK_NAME                  1027
#define INPF_ADDBOOK_BOOKNAME           1027
#define LBL_QUOTATION                   1028
#define BTN_REMOVE                      1028
#define BTN_REMOVE_BOOK                 1028
#define LBL_QUOTATION2                  1029
#define LBL_QUOTATION_RESUME            1029
#define INPF_ADDBOOK_AUTHORNAME         1029
#define BTN_QUOTE                       1030
#define INPF_ADDBOOK_ISBNCODE           1030
#define GBC_MANGA                       1031
#define GBC_CUELLO                      1032
#define GBC_PANTALON                    1033
#define IDC_COMBO1                      1034
#define CBC_HISTORY                     1034
#define CB_LISTEXEMPLARIES_SELECTEDBOOK 1034
#define LBC_DESCRIPTION                 1035
#define CB_ADDEXEMPLARY_SELECTEDBOOK    1035
#define LBL_STATIC                      1036
#define LBL_HISTORY_TEXT                1036
#define LB_BOOKS                        1039
#define GBC_ADD_BOOK                    1040
#define LBL_BOOK_NAME                   1041
#define LBL_STATIC_ADDBOOK_BOOKNAME     1041
#define LBL_BOOKS                       1042
#define GBC_BOOK_INFO                   1043
#define LBL_STATIC_BOOKINFO_NAME        1044
#define LBL_BOOKINFO_NAME               1045
#define LB_LISTEXEMPLARIES_EXEMPLARIES  1045
#define LBL_BOOKINFO_AUTHOR             1046
#define LBL_STATIC_EXEMPLARIES          1046
#define LBL_STATIC_BOOKINFO_AUTHOR      1047
#define GBC_LISTEXEMPLARIES             1047
#define LBL_BOOKINFO_ISBNCODE           1048
#define GBC_ADD_EXEMPLARY               1048
#define LBL_STATIC_BOOKINFO_ISBNCODE    1049
#define LBL_STATIC_ADDEXEMPLARY_EDITION 1049
#define LBL_BOOKINFO_EXEMPLARIESAMOUNT  1050
#define LBL_STATIC_ADDEXEMPLARY_UBICATION 1050
#define LBL_STATIC_BOOKINFO_EXEMPLARIESAMOUNT 1051
#define INPF_ADDEXEMPLARY_UBICATION     1051
#define LBL_STATIC_ADDBOOK_AUTHORNAME   1052
#define INPF_ADDEXEMPLARY_EDITION       1052
#define LBL_STATIC_ADDBOOK_ISBNCODE     1053
#define BTN_ADDEXEMPLARY_ADD            1053
#define BTN_LISTEXEMPLARIES_REMOVE      1054
#define LBL_STATIC_LISTEXEMPLARIES_SELECTEDBOOK 1055
#define LBL_STATIC_ADDEXEMPLARY_SELECTEDBOOK 1056
#define LBL_STATIC_ADDPARTNER_PARTNERNAME 1058
#define LBL_STATIC_ADDPARTNER_PARTNERLASTNAME 1059
#define INPF_ADDPARTNER_PARTNERNAME     1061
#define INPF_ADDPARTNER_PARTNERLASTNAME 1062
#define BTN_ADDPARTNER_ADD              1063
#define LBL_STATIC_PARTNERS             1064
#define GBC_PARTNERINFO                 1065
#define GBC_ADDPARTNER                  1066
#define LBL_STATIC_PARTNERINFO_NAME     1067
#define LBL_STATIC_PARTNERINFO_LASTNAME 1068
#define LBL_STATIC_PARTNERINFO_PARTNERID 1069
#define LBL_STATIC_PARTNERINFO_AMOUNT   1070
#define LBL_PARTNERINFO_NAME            1071
#define LBL_PARTNERINFO_LASTNAME        1072
#define LBL_PARTNERINFO_PARTNERID       1073
#define LBL_PARTNERINFO_AMOUNT          1074
#define LB_PARTNERS                     1075
#define BTN_PARTNERINFO_REMOVE          1076
#define LBL_STATIC_PARTNERINFO_PARTNERID2 1077
#define LBL_STATIC_PARTNERINFO_PARTNERTYPE 1077
#define LBL_PARTNERINFO_PARTNERID2      1078
#define LBL_PARTNERINFO_PARTNERTYPE     1078
#define GBC_PARTNERTYPE                 1079
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
